"""Rewrite §11 cell with clean newline handling — no embedded \n in f-strings."""
import json
from pathlib import Path

NB = Path(__file__).with_name('honest_eval_and_improve.ipynb')
nb = json.loads(NB.read_text(encoding='utf-8'))

lines = [
    "if 'batches' not in dir() or 'BASE_REGISTRY' not in dir():",
    "    raise RuntimeError('Run sections 1-3 first.')",
    "if '_train_on_audios2' not in dir():",
    "    raise RuntimeError('Run section 10 first (defines _train_on_audios2).')",
    "",
    "import re as _re_audit",
    "_RE_CAND = _re_audit.compile(r'^(.+)_(\\d{1,3})\\.[a-zA-Z0-9]+$')",
    "for _b in ['audios2','audios4','audios5']:",
    "    if 'candidate_id' not in batches[_b].columns:",
    "        batches[_b]['candidate_id'] = batches[_b]['filename'].astype(str).map(",
    "            lambda f: (_RE_CAND.match(f).group(1) if _RE_CAND.match(f) else None))",
    "",
    "# ---------- Score audios5 with both acoustic models trained on a2 only ----------",
    "def _score_audios5(name):",
    "    X_fn, factory = BASE_REGISTRY[name]",
    "    clf, sc, _ = _train_on_audios2(name, X_fn, factory, balanced=False)",
    "    df = batches['audios5'].copy()",
    "    p = clf.predict_proba(sc.transform(X_fn(df)))[:, 1]",
    "    return df[['filename','candidate_id','label_int']].assign(proba=p)",
    "",
    "w = _score_audios5('whisper_wp_xgb')",
    "v = _score_audios5('wavlm_whole_ft') if 'wavlm_whole_ft' in BASE_REGISTRY else None",
    "if v is None:",
    "    raise RuntimeError('wavlm_whole_ft not in BASE_REGISTRY — joint audit needs both models.')",
    "",
    "# ---------- Build joint table with audio_path ----------",
    "TARGET_BATCH = 'audios5'",
    "def _audio_path(cid, fn):",
    "    return str(NB_DIR / TARGET_BATCH / str(cid) / str(fn))",
    "",
    "joint = w.rename(columns={'proba':'whisper'}).merge(",
    "    v[['filename','proba']].rename(columns={'proba':'wavlm_ft'}),",
    "    on='filename')",
    "joint['avg']      = (joint['whisper'] + joint['wavlm_ft']) / 2",
    "joint['min_prob'] = joint[['whisper','wavlm_ft']].min(axis=1)",
    "joint['max_prob'] = joint[['whisper','wavlm_ft']].max(axis=1)",
    "joint['audio_path'] = [_audio_path(c, f) for c, f in zip(joint['candidate_id'], joint['filename'])]",
    "",
    "# ---------- Suspicion flags ----------",
    "POS_THR = 0.30   # labeled cheating + both models say <0.30 -> probably honest",
    "NEG_THR = 0.70   # labeled honest   + both models say >0.70 -> probably cheating",
    "joint['suspect_type'] = ''",
    "joint.loc[(joint['label_int']==1) & (joint['max_prob'] < POS_THR), 'suspect_type'] = 'pos_label_likely_honest'",
    "joint.loc[(joint['label_int']==0) & (joint['min_prob'] > NEG_THR), 'suspect_type'] = 'neg_label_likely_cheating'",
    "",
    "n_pos_total = int((joint['label_int']==1).sum())",
    "n_neg_total = int((joint['label_int']==0).sum())",
    "n_pos_susp  = int((joint['suspect_type']=='pos_label_likely_honest').sum())",
    "n_neg_susp  = int((joint['suspect_type']=='neg_label_likely_cheating').sum())",
    "",
    "BAR = '=' * 78",
    "print(BAR)",
    "print(' audios5 label-suspicion summary  (both models trained on audios2 only)')",
    "print(BAR)",
    "print(f'  total a5 audios scored : {len(joint)}')",
    "pos_pct = n_pos_susp / max(n_pos_total, 1) * 100",
    "neg_pct = n_neg_susp / max(n_neg_total, 1) * 100",
    "print(f'  labeled cheating       : {n_pos_total}   suspect (both models <{POS_THR}): {n_pos_susp}  ({pos_pct:.1f}% of positives)')",
    "print(f'  labeled honest         : {n_neg_total}   suspect (both models >{NEG_THR}): {n_neg_susp}  ({neg_pct:.1f}% of negatives)')",
    "",
    "SHOW = 10",
    "def _compact(df, sort_col, ascending, title):",
    "    if not len(df):",
    "        print()",
    "        print(f'  (no rows for: {title})')",
    "        return",
    "    cols = ['candidate_id','filename','whisper','wavlm_ft','avg','audio_path']",
    "    out = df.sort_values(sort_col, ascending=ascending).head(SHOW)[cols].copy()",
    "    out['whisper']  = out['whisper'].round(3)",
    "    out['wavlm_ft'] = out['wavlm_ft'].round(3)",
    "    out['avg']      = out['avg'].round(3)",
    "    print()",
    "    print(f'--- TOP {SHOW}: {title} ---')",
    "    with pd.option_context('display.max_columns', None, 'display.width', 240, 'display.max_colwidth', 80):",
    "        print(out.to_string(index=False))",
    "",
    "pos_df = joint[joint['label_int']==1].copy()",
    "neg_df = joint[joint['label_int']==0].copy()",
    "_compact(pos_df, 'min_prob', True,",
    "         'a5 LABELED CHEATING but both models score lowest (label may be honest)')",
    "_compact(neg_df, 'max_prob', False,",
    "         'a5 LABELED HONEST but both models score highest (label may be cheating)')",
    "",
    "# ---------- Per-candidate top-5 ----------",
    "joint['disagree'] = (joint['label_int'] - joint['avg']).abs()",
    "cand = joint.groupby('candidate_id').agg(",
    "    n=('filename','size'),",
    "    label_set=('label_int', lambda s: ','.join(map(str, sorted(s.unique())))),",
    "    mean_disagree=('disagree','mean'),",
    "    max_disagree =('disagree','max'),",
    ").sort_values('mean_disagree', ascending=False).head(5)",
    "print()",
    "print('--- TOP 5 candidates by mean model-vs-label disagreement ---')",
    "print(cand.round(3).to_string())",
    "",
    "# ---------- Save full ranked CSVs ----------",
    "out_path_pos = SAVE_DIR / 'a5_label_audit_positives.csv'",
    "out_path_neg = SAVE_DIR / 'a5_label_audit_negatives.csv'",
    "out_path_all = SAVE_DIR / 'a5_label_audit_all.csv'",
    "",
    "cols_save = ['candidate_id','filename','label_int','whisper','wavlm_ft','avg',",
    "             'min_prob','max_prob','suspect_type','audio_path']",
    "pos_df.sort_values('min_prob').to_csv(out_path_pos, columns=cols_save, index=False)",
    "neg_df.sort_values('max_prob', ascending=False).to_csv(out_path_neg, columns=cols_save, index=False)",
    "joint.sort_values('disagree', ascending=False).to_csv(out_path_all, columns=cols_save, index=False)",
    "",
    "print()",
    "print('Saved:')",
    "print(f'  {out_path_pos}    ({len(pos_df)} rows, sort by min_prob ASC -> most suspect on top)')",
    "print(f'  {out_path_neg}    ({len(neg_df)} rows, sort by max_prob DESC -> most suspect on top)')",
    "print(f'  {out_path_all}    ({len(joint)} rows, sorted by joint disagreement)')",
    "",
    "print()",
    "print('Decision rule:')",
    "print(f'  - Re-listen first to the rows in {out_path_pos.name} where suspect_type is set.')",
    "pct_int = int(round(pos_pct))",
    "print(f'  - If {n_pos_susp} of {n_pos_total} positives ({pct_int}%) really are mislabeled,')",
    "print('    fixing them and re-running section 6c should close most of the Rot B gap.')",
]
src = '\n'.join(lines)
nb['cells'][24]['source'] = [ln + '\n' for ln in src.split('\n')]
NB.write_text(json.dumps(nb, indent=1, ensure_ascii=False), encoding='utf-8')
print('§11 cell rewritten with clean newline handling')
